// DTCG token trees → CSS custom properties, using Figma slash notation
// (escaped: `--surface\/base`) so Figma-generated components resolve directly.
//
// Generic layered model: rootLayers render inside :root, lightLayers inside a
// prefers-color-scheme:light query. Order matters — earlier layers (primitives)
// define the var()s that later layers (semantic, components) reference.

import { flatten, isAlias } from './dtcg.js';
import { toCssColor } from './color.js';

// ['text','size','10'] → "--text\/size\/10". Spaces are not valid in CSS custom
// property names, so segment spaces collapse to hyphens (noted on export).
const cssVarName = (path) => '--' + path.map((s) => s.replace(/\s+/g, '-')).join('\\/');

const quoteFamily = (f) => (/\s/.test(f) ? `'${f}'` : f);

function formatValue(token) {
  const v = token.$value;
  if (isAlias(v)) {
    const refPath = v.slice(1, -1).split('.');
    return `var(${cssVarName(refPath)})`;
  }
  switch (token.$type) {
    case 'color':
      return toCssColor(v) ?? String(v);
    case 'fontFamily':
    case 'text':
      return (Array.isArray(v) ? v : [v]).map(quoteFamily).join(', ');
    case 'fontWeight':
    case 'number':
      return String(v);
    default:
      return String(v); // dimension strings ("10px") pass through
  }
}

function block(tree, indent) {
  return flatten(tree)
    .map(({ path, token }) => `${indent}${cssVarName(path)}: ${formatValue(token)};`)
    .join('\n');
}

// { rootLayers: [trees…], lightLayers: [trees…] }
export function toCss({ rootLayers = [], lightLayers = [] } = {}) {
  const header = `/*\n * Generated by Tessera from DTCG token files.\n * Property names use Figma slash notation (escaped) for drop-in compatibility.\n */`;

  const rootBody = rootLayers.map((t) => block(t, '  ')).filter(Boolean).join('\n\n');
  const lightBody = lightLayers.map((t) => block(t, '    ')).filter(Boolean).join('\n\n');

  let out = `${header}\n\n:root {\n${rootBody}\n}\n`;
  if (lightBody) {
    out += `\n@media (prefers-color-scheme: light) {\n  :root {\n${lightBody}\n  }\n}\n`;
  }
  return out;
}
